obj-$(CONFIG_MAKO_HOTPLUG) 	+= mako_hotplug.o
obj-$(CONFIG_MSM_SLEEPER) += msm-sleeper.o
obj-$(CONFIG_THUNDERPLUG_CONTROL) += thunderplug.o
obj-$(CONFIG_ALUCARD_HOTPLUG) += alucard_hotplug.o
obj-$(CONFIG_ZEN_DECISION) += msm_zen_decision.o
